### ISSUE TITLE
Bounce effect also trigger when close bottom sheet

### ISSUE THREAD

**Issue by anhquan291** [nomi9995/react-native-bottomsheet-reanimated#11]
Hi,
Thank you so much for this awesome library. 
However, I have a problem that my bs also trigger the bounce effect when I close it. It goes to the end of the screen and then bounces little bit. 
I will attach the video later. 
Thank you so much.

**Comment by nomi9995** [comment]
@anhquan291 thanks, I will remove the bounce effect on close.

**Comment by nomi9995** [comment]
@anhquan291 you can install `react-native-bottomsheet-reanimated@0.0.29` version
i have added `bounce` prop
you can manage bounce by change bounce value like 
`bounce={0}` or bounce={0.5}

**Comment by anhquan291** [comment]
> @anhquan291 you can install `react-native-bottomsheet-reanimated@0.0.29` version
> i have added `bounce` prop
> you can manage bounce by change bounce value like
> `bounce={0}` or bounce={0.5}

Thank you so much, I'll check it out. Have a great week
