### ISSUE TITLE
[Bug] BackDrop not working on version @0.0.30

### ISSUE THREAD

**Issue by anhquan291** [nomi9995/react-native-bottomsheet-reanimated#12]
Hi there,
It is me again. I'm now using the new version of your package. It is so nice, However the BackDrop doesn't work correctly. It only works on the first render. After that it doesn't

Thank you so much

**Comment by nomi9995** [comment]
@anhquan291 can you check `0.0.31`?

**Comment by anhquan291** [comment]
> @anhquan291 can you check `0.0.31`?

It works perfectly on 0.0.31. Thank you so much
