### ISSUE TITLE
Props are not optional (typescript)

### ISSUE THREAD

**Issue by peterjskaltsis** [nomi9995/react-native-bottomsheet-reanimated#23]
Hi there, 

Thanks for taking the time to put this package together. I tried using this recently in a TS project and noticed it was asking me to define all of the props.

This file...
https://github.com/nomi9995/react-native-bottomsheet-reanimated/blob/master/lib/typescript/src/index.d.ts

...has the TS type and it seems like many of the props have not been made optional here. Is this intentional?

Thanks in advance

**Comment by nomi9995** [comment]
@peterjskaltsis thanks for letting me know. I will make optional props

**Comment by nomi9995** [comment]
fixed by #26
