### ISSUE TITLE
Android Backdrop Dismiss Issue

### ISSUE THREAD

**Issue by wafda** [nomi9995/react-native-bottomsheet-reanimated#3]
When touch backdrop on android, bottom sheet not closed. Please fix this

**Comment by nomi9995** [comment]
@wafda I am too much busy with other projects. Just needs a PR :)

**Comment by nomi9995** [comment]
@wafda fixed in `0.0.35`

**Comment by lamlengend98** [comment]
> @wafda fixed in `0.0.35`

still not working on 0.2.0
