### ISSUE TITLE
Lack of examples and DOCs.

### ISSUE THREAD

**Issue by charitha95** [nomi9995/react-native-bottomsheet-reanimated#6]
Love your library and this is one of the best I've ever seen. yet This needs some documentation to get started. At least provide examples for the shown images in the read me.

**Comment by charitha95** [comment]
After playing around a bit I found out that the sample is there in the example code, yet styling and other features are lack in the doc. I'll try to raise a PR for docs in the rm file. Thanks

**Comment by nomi9995** [comment]
@charitha95 Thanks. I will welcome your PR
